INSERT INTO silver.medicare_part_d_prescribers
(
    Prscrbr_NPI,
    Prscrbr_Last_Org_Name,
    Prscrbr_First_Name,
    Prscrbr_City,
    Prscrbr_State_Abrvtn,
    Prscrbr_State_FIPS,
    Prscrbr_Type,
    Prscrbr_Type_Src,
    Brnd_Name,
    Gnrc_Name,
    Tot_Clms,
    Tot_30day_Fills,
    Tot_Day_Suply,
    Tot_Drug_Cst,
    Tot_Benes,
    GE65_Sprsn_Flag,
    GE65_Tot_Clms,
    GE65_Tot_30day_Fills,
    GE65_Tot_Drug_Cst,
    GE65_Tot_Day_Suply,
    GE65_Bene_Sprsn_Flag,
    GE65_Tot_Benes,
    data_year,
    source_file_name,
    ingestion_timestamp
)
SELECT
    NULLIF(TRIM(Prscrbr_NPI), ''),
    NULLIF(TRIM(Prscrbr_Last_Org_Name), ''),
    NULLIF(TRIM(Prscrbr_First_Name), ''),
    NULLIF(TRIM(Prscrbr_City), ''),
    NULLIF(TRIM(Prscrbr_State_Abrvtn), ''),
    NULLIF(TRIM(Prscrbr_State_FIPS), ''),
    NULLIF(TRIM(Prscrbr_Type), ''),
    NULLIF(TRIM(Prscrbr_Type_Src), ''),
    NULLIF(TRIM(Brnd_Name), ''),
    NULLIF(TRIM(Gnrc_Name), ''),
    Tot_Clms,
    Tot_30day_Fills,
    Tot_Day_Suply,
    Tot_Drug_Cst,
    Tot_Benes,
    GE65_Sprsn_Flag,
    GE65_Tot_Clms,
    GE65_Tot_30day_Fills,
    GE65_Tot_Drug_Cst,
    GE65_Tot_Day_Suply,
    GE65_Bene_Sprsn_Flag,
    GE65_Tot_Benes,
    data_year,
    source_file_name,
    ingestion_timestamp
FROM bronze.medicare_part_d_prescribers;
GO